### ISSUE TITLE
Add three dots (...) in the parameter list (variable number of arguments) of function GroupAIStateBase:convert_hostage_to_criminal

### ISSUE THREAD

**Issue by AmperAndSand** [segabl/pd2-hoplib#16]
The function `GroupAIStateBase:convert_hostage_to_criminal(unit, peer_unit)` in [groupaistatebase.lua](https://github.com/segabl/pd2-hoplib/blob/35fdd4ae073fd914963173d3c9116e195dd15813/lua/groupaistatebase.lua) is also hooked by PocoHud, Full Speed Swarm, Intimidated Outlines (Unsynced version), and also probably the other Intimidated Outlines versions/modifications too, including the original Intimidated Outlines, Less Confusing Intimidated Outlines and Anti Intimidated Outlines.

Since it is hooked by many mods, to increase compatibility, it should also be defined with  three dots (`...`) in the parameter list so that it can take a variable number of arguments. The other hooked functions by HopLib already have `...` in the parameter list, but this function doesn't.

e.g., `function GroupAIStateBase:convert_hostage_to_criminal(unit, peer_unit, ...)`
`convert_hostage_to_criminal_original(self, unit, peer_unit, ...)`

**Comment by segabl** [comment]
Yes, this is an oversight on my part. Will fix that and should be included in the next release.
