### ISSUE TITLE
Possible Crash From unitnetworkhandler.lua

### ISSUE THREAD

**Issue by Jaco909** [segabl/pd2-hoplib#19]
Since the update issued on the 12th, I've crashed multiple times, with it originating from the file _unitnetworkhandler.lua_. 

`[string "lib/network/handlers/unitnetworkhandler.lua"]:1714: attempt to perform arithmetic on local 'rot_speed_mul' (a nil value)`

Dived through the mods folder and this was the only mod active to have this file. The mod was also updated the same day the crashes stared, and I've not suffered any crashes since removing it, so I'm fairly confident that it's coming from this mod. Crash.txt file attached.
[crash.txt](https://github.com/segabl/pd2-hoplib/files/5541904/crash.txt)

**Comment by segabl** [comment]
From what I can gather this crash is caused by someone placing a sentry gun with an invalid rotation speed level. If you have any mods affecting sentry guns (or if you play with someone that has sentry gun mods) it is most likely caused by that, as this mod doesn't change any sentry gun stats

**Comment by Jaco909** [comment]
Thanks, that definitely narrows down the culprit!
