### ISSUE TITLE
Broken “Partners In Crime”

### ISSUE THREAD

**Issue by lixal** [segabl/pd2-hoplib#24]
After the update on December 8 in the file “copdamage.lua” - it looks like the game began to ignore the skill “Partners In Crime” or for some unknown to me reason - the health of Jokers began to melt literally in front of my eyes in seconds! I rolled back the version to November 28 and everything became normal.

PS: I also use the Jokermon mod.

**Comment by lixal** [comment]
> Does this only happen with Jokers spawned via Jokermon or in general?

In general!

**Comment by segabl** [comment]
So far I have not been able to reproduce it and the change from December 8 shouldn't be able to cause anything like that

**Comment by segabl** [comment]
Compare and see how it behaves without Jokermon, if you want you can record a video too

**Comment by lixal** [comment]
> Compare and see how it behaves without Jokermon, if you want you can record a video too

Experimentally, I found out that this is nothing more than a trivial coincidence: jokers accidentally started bumping into a whole squad of ZEAL Heavy SWAT, which shot more painfully and more often than usual, causing them to literally die like flies! And I put it down to the fact that this stuff started happening more often when HopLib was updated!
