### ISSUE TITLE
FBI Heavy SWAT renaming causes crashing

### ISSUE THREAD

**Issue by BreakinBenny** [segabl/pd2-hoplib#5]
It's not an issue with your mod, per say, but when I try to make NameProvider.lua allow modifying the string representing the FBI Heavy SWAT (Maximum Force Responder in PC terms), it crashes. I believe part of the problem has to be that there's already an enemy tweak table called "fbi".

What do you think, @segabl?

**Comment by segabl** [comment]
Depends entirely on what you're doing

**Comment by BreakinBenny** [comment]
What I did was modify the local name that should rename the then capitalized tweak table for enemies. First I did this with "fbi_heavy_swat" (internal name for MFRs), only to have it crash, next I tried doing it with "fbi_heavy" instead… here's an example of what I tried:

`local name = tweak:gsub("_female", ""):pretty(true):gsub("fbi_heavy", "MFR"):gsub("Swat", "SWAT"):gsub("Fbi", "FBI")`

And guess what? It still crashes. My point is that the FBI Heavy SWAT (which they're even called if they're brought in by GenSec's units on Mayhem/Death Wish) should be named MFRs, since otherwise it'd be a bit strange.

**Comment by segabl** [comment]
I don't know why it crashes but it won't find "fbi_heavy" after the call to pretty(true) since that removes underscores and capitalizes names. the easiest solution would be to just add the name to self._names like:
fbi_heavy_swat = { default = "MFR Swat" }

**Comment by BreakinBenny** [comment]
Here's my crashlog from yesterday:

`Wed Mar 14 18:29:48 2018


Application has crashed: C++ exception
mods/HopLib/HopLib.lua:27: attempt to index local 'provider' (a nil value)



SCRIPT STACK

set_joker_name() @mods/Keepers Joker Names/joker_names.lua:108
check_peer_name_override() @mods/Keepers Joker Names/joker_names.lua:120
kpr_original_unitnetworkhandler_markminion() @mods/Keepers Joker Names/joker_names.lua:187
@mods/Keepers/lua/unitnetworkhandler.lua:11


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.87.537.
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[23.21.13.9101]
	Language : english
	Memory :     8132MB 48KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Högtalare (High Definition Audio Device))`

**Comment by segabl** [comment]
Well, seems like you somehow created  syntax error in NameProvider that causes it to not load properly

**Comment by BreakinBenny** [comment]
Doing it this way causes a crash:

function NameProvider:_init_names()
  self._names = {
    fbi_heavy_swat = { default = "MFR" },

**Comment by segabl** [comment]
Asumming the other entries are still there it should be fine, if it's just that though, then of course it would crash due to invalid syntax

**Comment by BreakinBenny** [comment]
But it doesn't make sense; heavy_swat and fbi_heavy_swat are two different types of Heavy SWAT units, the former is a yellow-dorning MPD/ZEAL SWAT, the latter is the Maximum Force Responder.

I hope you have better luck than I do, segabl. I won't hold my breath for it though.

**Comment by segabl** [comment]
No, that's not how the code works at all. First it checks the self._names table if the name already exists and uses that one, if it doesn't, then it constructs a new name from the tweak_table id and puts it into self._names. A crash is most likely caused by some syntax error or some other code problem.

**Comment by BreakinBenny** [comment]
You can check my forked version of NameProvider.lua and verify what I'm doing wrong then, since grasping your system is as difficult as grasping the true form of Giygas' attack.

**Comment by BreakinBenny** [comment]
Further testing shows that the MFR unit spawns without problem, but shortly after one appears PAYDAY 2 crashes with this message.

```
Mon Mar 19 22:19:39 2018


Application has crashed: C++ exception
mods/HopLib/HopLib.lua:27: attempt to index local 'provider' (a nil value)
```


I mean, what? Why does it not accept the "fbi_heavy_" part but will gladly eat that "_female" shit?

**Comment by segabl** [comment]
suggests the name provider hasn't been created (probably due to syntax errors in name provider), you should check the blt log for errors

**Comment by BreakinBenny** [comment]
Aha! A comma is missing after the one for escort_undercover, now I see.
